import type { Lang } from "@/components/wellness/i18n";

export type AppStrings = typeof appStrings.en;

export const appStrings = {
  en: {
    appName: "Milestone",
    tagline: "Your calm AI companion through exam season.",
    heroSub:
      "Journal openly, log your mood, and talk to an empathetic AI tuned for students preparing for NEET, JEE, CUET, CAT, GATE, UPSC and board exams.",
    signIn: "Sign in",
    signUp: "Create account",
    email: "Email",
    password: "Password",
    displayName: "Your name",
    examTarget: "Exam you're preparing for",
    examTargetPh: "e.g. NEET 2026, JEE Advanced, CAT…",
    continueGoogle: "Continue with Google",
    orDivider: "or",
    signOut: "Sign out",
    haveAccount: "Already have an account? Sign in",
    noAccount: "New here? Create an account",
    nav: {
      home: "Home",
      chat: "Companion chat",
      journal: "Journal",
      settings: "Settings",
      newChat: "New conversation",
      conversations: "Conversations",
    },
    dashboard: {
      greetMorning: (n: string) => `Good morning, ${n}.`,
      greetAfternoon: (n: string) => `Good afternoon, ${n}.`,
      greetEvening: (n: string) => `Good evening, ${n}.`,
      moodTitle: "How are you feeling right now?",
      moodHint: "A quick check-in helps the AI notice patterns over time.",
      moodNotePh: "One word, optional…",
      logMood: "Log mood",
      moodLogged: "Mood saved. Take a breath.",
      recentMoods: "Recent check-ins",
      noMoods: "No mood logs yet.",
      startChat: "Start a conversation",
      openJournal: "Open journal",
      quickActions: "Quick actions",
      recentEntries: "Recent journal entries",
      noEntries: "Your journal is empty. Write your first entry whenever you're ready.",
    },
    chat: {
      title: "Companion chat",
      empty: "Share what's on your mind. I'm here, no judgment.",
      placeholder: "Type a message…",
      send: "Send",
      thinking: "Thinking…",
      stop: "Stop",
      newThread: "New conversation",
      deleteThread: "Delete conversation",
      confirmDelete: "Delete this conversation? This cannot be undone.",
    },
    journal: {
      title: "Daily journal",
      sub: "Write freely. The AI will surface hidden triggers and a small next step.",
      placeholder:
        "Today I felt… The exam is in… I'm worried that… Recently I noticed…",
      analyze: "Analyze with AI",
      analyzing: "Reading your words gently…",
      triggers: "Hidden triggers",
      reassurance: "A gentle reminder",
      coping: "One small step",
      moodScore: "Detected emotional tone",
      saved: "Saved to your journal.",
    },
    moodLabels: ["Very low", "Low", "Okay", "Good", "Great"],
    crisis:
      "If you are in crisis or thinking of harming yourself, please reach out now. iCall +91 9152987821 · Vandrevala Foundation 1860-2662-345 (free, 24/7).",
  },
  hi: {
    appName: "माइलस्टोन",
    tagline: "परीक्षा के दिनों में आपका शांत एआई साथी।",
    heroSub:
      "खुलकर लिखें, अपना मूड दर्ज करें, और NEET, JEE, CUET, CAT, GATE, UPSC तथा बोर्ड परीक्षाओं की तैयारी कर रहे छात्रों के लिए तैयार सहानुभूतिपूर्ण एआई से बात करें।",
    signIn: "साइन इन",
    signUp: "खाता बनाएँ",
    email: "ईमेल",
    password: "पासवर्ड",
    displayName: "आपका नाम",
    examTarget: "आप किस परीक्षा की तैयारी कर रहे हैं",
    examTargetPh: "जैसे, NEET 2026, JEE Advanced, CAT…",
    continueGoogle: "Google से जारी रखें",
    orDivider: "या",
    signOut: "साइन आउट",
    haveAccount: "खाता पहले से है? साइन इन करें",
    noAccount: "नए हैं? खाता बनाएँ",
    nav: {
      home: "मुखपृष्ठ",
      chat: "साथी चैट",
      journal: "जर्नल",
      settings: "सेटिंग्स",
      newChat: "नई बातचीत",
      conversations: "बातचीत",
    },
    dashboard: {
      greetMorning: (n: string) => `शुभ प्रभात, ${n}.`,
      greetAfternoon: (n: string) => `नमस्ते, ${n}.`,
      greetEvening: (n: string) => `शुभ संध्या, ${n}.`,
      moodTitle: "अभी आप कैसा महसूस कर रहे हैं?",
      moodHint: "एक छोटा सा चेक-इन एआई को समय के साथ पैटर्न समझने में मदद करता है।",
      moodNotePh: "एक शब्द, वैकल्पिक…",
      logMood: "मूड दर्ज करें",
      moodLogged: "मूड सहेज लिया। एक गहरी साँस लें।",
      recentMoods: "हाल के चेक-इन",
      noMoods: "अभी तक कोई मूड लॉग नहीं।",
      startChat: "बातचीत शुरू करें",
      openJournal: "जर्नल खोलें",
      quickActions: "त्वरित क्रियाएँ",
      recentEntries: "हाल की जर्नल प्रविष्टियाँ",
      noEntries: "आपकी जर्नल खाली है। जब आप तैयार हों, पहली प्रविष्टि लिखें।",
    },
    chat: {
      title: "साथी चैट",
      empty: "जो मन में है, साझा करें। मैं यहाँ हूँ, बिना किसी फैसले के।",
      placeholder: "संदेश लिखें…",
      send: "भेजें",
      thinking: "सोच रहा हूँ…",
      stop: "रोकें",
      newThread: "नई बातचीत",
      deleteThread: "बातचीत हटाएँ",
      confirmDelete: "इस बातचीत को हटाएँ? यह वापस नहीं आएगी।",
    },
    journal: {
      title: "दैनिक जर्नल",
      sub: "खुलकर लिखें। एआई छिपे हुए ट्रिगर्स और एक छोटा अगला कदम सुझाएगा।",
      placeholder:
        "आज मुझे लगा… परीक्षा है… मुझे चिंता है कि… हाल ही में मैंने देखा…",
      analyze: "एआई से विश्लेषण करें",
      analyzing: "आपके शब्दों को धीरे-धीरे पढ़ रहे हैं…",
      triggers: "छिपे हुए ट्रिगर",
      reassurance: "एक कोमल याद",
      coping: "एक छोटा कदम",
      moodScore: "भावनात्मक स्वर",
      saved: "आपकी जर्नल में सहेज लिया गया।",
    },
    moodLabels: ["बहुत निम्न", "निम्न", "ठीक", "अच्छा", "बहुत अच्छा"],
    crisis:
      "यदि आप संकट में हैं या स्वयं को नुकसान पहुँचाने के बारे में सोच रहे हैं, कृपया अभी संपर्क करें। iCall +91 9152987821 · वंद्रेवाला फ़ाउंडेशन 1860-2662-345 (निःशुल्क, 24/7)।",
  },
} as const;

export function s(lang: Lang) {
  return appStrings[lang];
}